version: '3.6'

services:
  web:
    build:
      context: .
      dockerfile: src/nsupdate/Dockerfile.prod
    command: gunicorn nsupdate.wsgi:application --bind 0.0.0.0:8000
    # volumes:
    #   - ./src/nsupdate/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

volumes:
  postgres_data: